committing a changed Route class and MapState class
cuappdev/ithaca-transit-android-v2 pull request #6
Opened 2019-10-30 02:23 UTC by aasthashah999

## Overview

I created and file out the `Map State` class. I added four states to represent UI changes and network calls. The states are:
1. `LaunchState` which is a blank map before any network calls are made. This is the map without any route drawn on or bus stops marked. 
2. `BusStopsShown` is a state that is launched the very first time the app is opened after the `LaunchState`. It shows all the bus stops in Ithaca. 
3. `TripOptions` is the state shown after the user selected a destination. It shows the first bus route and a walking route. 
4. `SelectedTrip` is the state that shows the visual representation of the chosen trip. 

## Changes Made
The MapState classes were added, and the Arrays in Route were changed to Lists. 

## Next Steps (delete if not applicable)
Not entirely sure if MapState includes the correct fields. It might need to Trip objects to account for the RouteObjects state. Furthermore, I need to figure what the map will display when the person is already on the bus. The map will have to show a shortening path most likely.

2019-10-30 19:13 UTC, ningning621 commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +import java.util.*
let's try to avoid importing `java.util`; just import the library that you need

2019-10-30 19:15 UTC, ningning621 commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +) {}
i'm fairly certain that this is just be `sealed class MapState(val trip = Trip ) `

think of `val` as a constant, if you give it a default object then technically the value cannot be modified!

2019-10-30 19:16 UTC, ningning621 commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +class LaunchState():MapState()
think of `MapState` as a parent class. if `MapState` has `Trip` as a param, then all its children need to have `Trip` as a param as well!

2019-10-30 19:18 UTC, ningning621 commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +class LaunchState():MapState()
should be `class LaunchState(trip : Trip) : MapState(trip)`

2019-10-30 19:32 UTC, ningning621 commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +class BusStopsShown():MapState() {}
can just do `class BusStopsShown():MapState()`

2019-10-30 19:33 UTC, ningning621 commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/Route.kt
>  import java.util.*
not sure how we missed this but please import only the classes that you need!

2019-10-30 19:48 UTC, ningning621 requested changes
looks like a good step in the right direction, please review this [comment](https://github.com/cuappdev/ithaca-transit-android-v2/pull/6/files#r34081116) and make this change everywhere else where it might apply

2019-10-31 00:22 UTC, Haichen-Wang reviewed
Looks good overall! But I would suggest adding in some comments for each class describing what it is used for

2019-10-31 20:58 UTC, young-k reviewed
nit, can you capitalize this PR title, and make sure that in the future branches are titled properly –– this should be `aastha/map-state`

2019-11-02 21:42 UTC, JiangoJ commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +    busStops: List<Coordinate>,
Could this busStop info be a Location Object?

2019-11-02 21:54 UTC, JiangoJ approved these changes

2019-11-02 21:56 UTC, ningning621 approved these changes
lgtm!

2019-11-02 22:01 UTC, merged

2019-11-02 22:02 UTC, Haichen-Wang requested changes

2019-11-02 22:02 UTC, Haichen-Wang commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +//State that represents the empty map before a network call has been
Comments should be like `// ...` 
i.e. There should be a space after "//"

2019-11-02 22:02 UTC, Haichen-Wang commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +//State that represents the map with all bus stops marked and marks the user's current location.
Same here and below

2019-11-02 22:02 UTC, Haichen-Wang commented on app/src/main/java/com/example/ithaca_transit_android_v2/Models/MapState.kt
> +import java.util.Date
Do we need this import here?